apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-keycloak.fullname" . }}-keycloak
  labels:
    {{- include "oauth2-keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.keycloak.admin.username | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.admin.password | quote }}
