apiVersion: v1
kind: Service
metadata:
  name: {{ include "oauth2-keycloak.fullname" . }}-nginx
  labels:
    {{- include "oauth2-keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  selector:
    {{- include "oauth2-keycloak.componentSelectorLabels" (dict "ctx" . "component" "nginx") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
