apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-keycloak.fullname" . }}-oauth2-proxy
  labels:
    {{- include "oauth2-keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
type: Opaque
stringData:
  OAUTH2_PROXY_CLIENT_ID: {{ .Values.oauth2Proxy.clientId | quote }}
  OAUTH2_PROXY_CLIENT_SECRET: {{ .Values.oauth2Proxy.clientSecret | quote }}
  OAUTH2_PROXY_COOKIE_SECRET: {{ .Values.oauth2Proxy.cookieSecret | quote }}
